/**
 * DENTIVA — asset pipeline.
 *
 * Two jobs:
 *
 * 1. `src/renderer/fonts/fonts.css` is generated from the `@fontsource` packages
 *    so the window and the printed documents use the same Inter + Noto Sans
 *    Bengali weights while offline (no Google Fonts, no network).
 *
 * 2. `src/server/generated/assets.js` is rewritten with the renderer, the fonts
 *    and the shared i18n catalogue embedded as strings/bytes, which is what
 *    makes the compiled executable self-contained.
 *
 *   bun run gen:assets            embed everything
 *   bun run gen:assets --stub     restore the empty checked-in stub
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { extname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const RENDERER = join(ROOT, 'src/renderer');
const GENERATED = join(ROOT, 'src/server/generated/assets.js');

/** Weights shipped with the app (kept small: the UI uses 400–700). */
const WEIGHTS = [400, 500, 600, 700];

/** Latin UI + Bengali UI, with the subsets each family publishes. */
const FONT_FACES = [
  { family: 'Inter', package: '@fontsource/inter', subsets: ['latin', 'latin-ext'], stem: 'inter' },
  { family: 'Noto Sans Bengali', package: '@fontsource/noto-sans-bengali', subsets: ['bengali', 'latin'], stem: 'noto-sans-bengali' },
];

/** Latin/Bengali/Greek/Cyrillic coverage so the browser never falls back mid-line. */
const UNICODE_RANGES = {
  latin: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  'latin-ext': 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  bengali: 'U+0964-0965,U+0980-09FE,U+1CF7,U+1CD0-1CF9,U+200C-200D,U+20A8,U+20B9,U+20F0,U+25CC,U+A8F1',
};

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.txt': 'text/plain; charset=utf-8',
};

const isText = (ext) => ['.html', '.css', '.js', '.mjs', '.json', '.svg', '.txt'].includes(ext);

/** Every file under `dir`, as paths relative to it, `/`-separated. */
function walk(dir, base = dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full, base));
    else out.push(relative(base, full).split('\\').join('/'));
  }
  return out;
}

/* --------------------------------------------------------------- fonts.css */

function fontSources() {
  const files = [];
  for (const face of FONT_FACES) {
    const dir = join(ROOT, 'node_modules', face.package, 'files');
    if (!existsSync(dir)) continue;
    for (const weight of WEIGHTS) {
      for (const subset of face.subsets) {
        const name = `${face.stem}-${subset}-${weight}-normal.woff2`;
        if (existsSync(join(dir, name))) files.push({ face, weight, subset, name, path: join(dir, name) });
      }
    }
  }
  return files;
}

function writeFontsCss() {
  const files = fontSources();
  if (!files.length) {
    console.warn('[gen-assets] @fontsource packages are missing — run `bun install` first');
    return { count: 0, files: /** @type {any[]} */ ([]) };
  }
  const blocks = files.map(({ face, weight, subset, name }) => [
    '@font-face {',
    `  font-family: '${face.family}';`,
    '  font-style: normal;',
    `  font-weight: ${weight};`,
    '  font-display: swap;',
    `  src: url('/fonts/${name}') format('woff2');`,
    `  unicode-range: ${UNICODE_RANGES[subset]};`,
    '}',
  ].join('\n'));
  const header = [
    '/**',
    ' * Generated by `bun scripts/gen-assets.mjs` — do not edit by hand.',
    ' *',
    ' * Inter (Latin UI) and Noto Sans Bengali (Bangla UI) are bundled with the',
    ' * application: the clinic needs no internet connection and no fonts installed',
    ' * on the computer for either language to render correctly.',
    ' */',
    '',
  ].join('\n');
  const target = join(RENDERER, 'fonts/fonts.css');
  mkdirSync(join(RENDERER, 'fonts'), { recursive: true });
  writeFileSync(target, `${header}${blocks.join('\n\n')}\n`, 'utf8');
  return { count: files.length, files };
}

/* ------------------------------------------------------------ asset bundle */

function embed(buffer, ext) {
  if (isText(ext)) return { type: MIME[ext] ?? 'text/plain; charset=utf-8', text: buffer.toString('utf8') };
  return { type: MIME[ext] ?? 'application/octet-stream', base64: buffer.toString('base64') };
}

/** @param {{ files: any[] }} fonts */
function buildAssets(fonts) {
  /** @type {Record<string, any>} */
  const assets = {};
  let bytes = 0;

  const add = (key, path) => {
    const buffer = readFileSync(path);
    assets[key] = embed(buffer, extname(key).toLowerCase());
    bytes += buffer.length;
  };

  for (const name of walk(RENDERER)) {
    if (name.startsWith('fonts/')) continue;
    add(name, join(RENDERER, name));
  }
  add('fonts/fonts.css', join(RENDERER, 'fonts/fonts.css'));
  for (const font of fonts.files ?? []) add(`fonts/${font.name}`, font.path);

  // The window imports the shared catalogue (and its data) over `/shared/**`.
  for (const name of ['i18n/index.js', 'i18n/en.js', 'i18n/bn.js', 'constants.js', 'errors.js']) {
    add(`shared/${name}`, join(ROOT, 'src/shared', name));
  }
  // Shipped configuration that must travel inside the executable.
  for (const name of ['clinic-defaults.json']) {
    add(`resources/${name}`, join(ROOT, 'resources', name));
  }
  bytes += 0;

  const header = [
    '/**',
    ' * Generated asset map — created by `bun scripts/gen-assets.mjs`.',
    ' *',
    ' * The packaged build embeds the renderer (HTML/CSS/JS, fonts, icon) here so the',
    ' * executable is self-contained and works with no files on disk beside it. The',
    ' * checked-in copy is intentionally empty: running from source reads the real',
    ' * files from `src/renderer` and `node_modules` instead.',
    ' *',
    ' * @type {Record<string, { type: string, text?: string, base64?: string }>}',
    ' */',
  ].join('\n');

  const entries = Object.entries(assets).map(([key, value]) => {
    const payload = value.text !== undefined
      ? `text: ${JSON.stringify(value.text)}`
      : `base64: '${value.base64}'`;
    return `  ${JSON.stringify(key)}: { type: ${JSON.stringify(value.type)}, ${payload} },`;
  });

  return {
    module: `${header}\nexport const ASSETS = {\n${entries.join('\n')}\n};\n\nexport default ASSETS;\n`,
    files: Object.keys(assets).length,
    bytes,
  };
}

function writeStub() {
  const stub = [
    '/**',
    ' * Generated asset map — created by `bun scripts/gen-assets.mjs`.',
    ' *',
    ' * The packaged build embeds the renderer (HTML/CSS/JS, fonts, icon) here so the',
    ' * executable is self-contained and works with no files on disk beside it. The',
    ' * checked-in copy is intentionally empty: running from source reads the real',
    ' * files from `src/renderer` and `node_modules` instead.',
    ' *',
    ' * @type {Record<string, { type: string, text?: string, base64?: string }>}',
    ' */',
    'export const ASSETS = {};',
    '',
    'export default ASSETS;',
    '',
  ].join('\n');
  mkdirSync(join(ROOT, 'src/server/generated'), { recursive: true });
  writeFileSync(GENERATED, stub, 'utf8');
  return stub.length;
}

const args = process.argv.slice(2);
if (args.includes('--stub')) {
  writeStub();
  console.log('✔ asset map reset to the empty stub (run from source)');
} else {
  const fonts = writeFontsCss();
  const bundle = buildAssets(fonts);
  mkdirSync(join(ROOT, 'src/server/generated'), { recursive: true });
  writeFileSync(GENERATED, bundle.module, 'utf8');
  console.log(`✔ fonts.css — ${fonts.count} font file(s)`);
  console.log(`✔ embedded assets — ${bundle.files} file(s), ${(bundle.bytes / 1024).toFixed(0)} kB`);
}
